export const weeks = ['일', '월', '화', '수', '목', '금', '토']
export const days = [
    {
        day: 29,
        thisMonth: false,
        weekend: false,
        selected: false,
    },
    {
        day: 30,
        thisMonth: false,
        weekend: false,
        selected: false,
    },
    {
        day: 31,
        thisMonth: false,
        weekend: false,
        selected: false,
    },
    {
        day: 1,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 2,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 3,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 4,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 5,
        thisMonth: true,
        weekend: true,
        selected: false,
    },
    {
        day: 6,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 7,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 8,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 9,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 10,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 11,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 12,
        thisMonth: true,
        weekend: true,
        selected: false,
    },
    {
        day: 13,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 14,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 15,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 16,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 17,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 18,
        thisMonth: true,
        weekend: false,
        selected: true,
    },
    {
        day: 19,
        thisMonth: true,
        weekend: true,
        selected: false,
    },
    {
        day: 20,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 21,
        thisMonth: true,
        weekend: false,
        selected: false,
    },

    {
        day: 22,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 23,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 24,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 25,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 26,
        thisMonth: true,
        weekend: true,
        selected: false,
    },
    {
        day: 27,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 28,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 29,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 30,
        thisMonth: true,
        weekend: false,
        selected: false,
    },
    {
        day: 1,
        thisMonth: false,
        weekend: false,
        selected: false,
    },
    {
        day: 2,
        thisMonth: false,
        weekend: false,
        selected: false,
    },
]
export const weekend = [5, 12, 19, 26]
